### ISSUE TITLE
Bug: Starlite CLI cannot import project

### ISSUE THREAD

**Issue by ikollipara** [starlite-api/starlite#1031]
**Describe the bug**
I have a very minimal hello world application in Starlite, using Poetry.
I have installed python-dotenv, and created a base env file that points to the poetry package.
However, whenever I run `starlite info` I get an import error in the cli.
I've attempted to debug this through the use of print statements, augmenting python's `sys.path`, as well as importing other installed packages, like `pydantic`. 

I am able to import my files using `importlib.import_module` from the python REPL, but am unable to in the cli.

```python
from starlite import Starlite, get

@get("/")
def hello() -> str:
    return "world"

app = Starlite(route_handlers=[hello])
```

**To Reproduce**
1. Generate a Poetry project
2. Install `starlite[full]`
3. Install `python-dotenv`
4. Install `uvicorn`
5. Create a `.env` file pointing to the poetry package
6. Create a basic hello world file in the `__init__.py` (see attachment)
7. Run `starlite info`

**Additional context**
I am on Starlite Version 1.48.1
Here is the full error message. For context the Poetry package is named `starlite_playground`
```
Using Starlite app from env: 'starlite_playground:app'
Traceback (most recent call last):
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/bin/starlite", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/starlite/cli.py", line 347, in cli
    ctx.obj = StarliteEnv.from_env(app_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/starlite/cli.py", line 102, in from_env
    loaded_app = _autodiscover_app(getenv("STARLITE_APP"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/starlite/cli.py", line 210, in _autodiscover_app
    return _load_app_from_path(app_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikollipara/Documents/GitHub/starlite-playground/.venv/lib/python3.11/site-packages/starlite/cli.py", line 192, in _load_app_from_path
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'starlite_playground'
```

**Comment by provinzkraut** [comment]
I can't reproduce this on my end. Can you share your `pyproject.toml` and directory layout?

Although I have a hunch what's going on. 
> Create a .env file pointing to the poetry package

Does running a separate `poetry install` solve your problem? If you set `STARLITE_APP` to the name of the package as defined in poetry, it could require that this package is actually installed in the current environment, depending on the directory structure / naming.

**Comment by ikollipara** [comment]
Yes, just running poetry install fixed the problem. Thank you for the help!

From what I understand, and correct me if I'm wrong, but since my application was not on the system path that was used by starlite's cli, it couldn't detect the file to run, therefore throwing that import error.

**Comment by provinzkraut** [comment]
Yes, that's correct. However, I think we should definitely support this and it's a relatively easy fix. I'll put up a PR for this.

**Comment by provinzkraut** [comment]
@ikollipara Can you check out the PR I made at #1038 and confirm that it solves your issue?
