### ISSUE TITLE
204 status code not handled properly

### ISSUE THREAD

**Issue by vrslev** [starlite-api/starlite#154]
Exception raises when route returns response with 204 No Content status.
<details>

```console
INFO:     127.0.0.1:58657 - "DELETE / HTTP/1.1" 204 No Content
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlite/app.py", line 149, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlite/asgi.py", line 70, in __call__
    await route.handle(scope=scope, receive=receive, send=send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlite/routes.py", line 161, in handle
    await response(scope, receive, send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlette/responses.py", line 167, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 462, in send
    output = self.conn.send(event)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/h11/_connection.py", line 510, in send
    data_list = self.send_with_data_passthrough(event)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/h11/_connection.py", line 543, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlite/app.py", line 151, in __call__
    await self.handle_exception(scope=scope, receive=receive, send=send, exc=e)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlite/app.py", line 165, in handle_exception
    await response(scope=scope, receive=receive, send=send)
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/starlette/responses.py", line 160, in __call__
    await send(
  File "/private/tmp/starlite-fetch-error/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 452, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'http.response.body', but got 'http.response.start'.
```

</details>

This example fails:

```python
from starlite import CORSConfig, Starlite, delete


@delete()
async def route() -> None:
    return None


app = Starlite(route_handlers=[route], debug=True)
```

This one does fail too. Additionally, Starlite resolved 204, but there is some content (200):

```python
from starlite import CORSConfig, Starlite, delete


@delete()
async def route() -> str:
    return "Hello!"


app = Starlite(route_handlers=[route], debug=True)
```

Starlette works fine, so the problem is definitely with Starlite:

```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route


async def route(request):
    return PlainTextResponse("", status_code=204)


app = Starlette(
    debug=True,
    routes=[Route("/", route, methods=["DELETE"])],
)
```

**Comment by peterschutt** [comment]
> Starlite resolved 204, but there is some content (200):

There's not really any resolving afaik, if you don't specify different, the status of the response is dynamically set in `HTTPRouteHandler.__init__()`:

```python
        if status_code:
            self.status_code = status_code
        elif isinstance(self.http_method, list):
            self.status_code = HTTP_200_OK
        elif self.http_method == HttpMethod.POST:
            self.status_code = HTTP_201_CREATED
        elif self.http_method == HttpMethod.DELETE:
            self.status_code = HTTP_204_NO_CONTENT
```

So you'd need `@delete(status_code=200)`.

As far as the empty response goes, I've added a failing test here: https://github.com/starlite-api/starlite/compare/main...issue-154-204-none-response

Inspecting the response in the test shows that `response.content` is `b'null'`, which just smells to me like the `None` response from the handler is getting handed straight to `orjson.dump()`. [`null` is a valid json response](https://stackoverflow.com/a/39124954/6560549), but I think it's pretty safe to assume that if a handler is configured to return a 204 and the handler returns `None` that the developer wants that to be an empty response.

**Comment by vrslev** [comment]
> So you'd need @delete(status_code=200).

Maybe 204 status should be resolved based on SignatureModel? If return type annotation is `None`, then set 204?

**Comment by Goldziher** [comment]
> > So you'd need `@delete(status_code=200)`.
> 
> Maybe 204 status should be resolved based on SignatureModel? If return type annotation is `None`, then set 204?

No, these are API semantics we can't enforce.

**Comment by vrslev** [comment]
What about defaulting to 200? Let the developer decide if 204 should be returned.

**Comment by peterschutt** [comment]
What if we allow the `Starlite` constructor to receive a mapping of http verbs to response status, and fallback to current behavior if not provided. So you could do:

`Starlite(..., default_response_codes={"DELETE": HTTP_204_NO_CONTENT})`

We return the deleted object from `DELETE` as sometimes it can be useful, so I've wrapped `starlite.delete` locally to override that to be `200` in all cases. Having a way to define those defaults at the application level seems logical.

**Comment by peterschutt** [comment]
This is really a different issue though, want to open a new one?

**Comment by vrslev** [comment]
It is not really useful for me. The main issue is handling `None` with 204

**Comment by peterschutt** [comment]
OK well that's already sorted and will be in the next release.
