### ISSUE TITLE
Bug: Recursion error from OpenAPIConfig.create_examples

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#196]
I haven't had a chance to debug this at all, as I only turned the feature on to test something unrelated.

This is at the bottom of the traceback:

```
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 513, in build
app_1  |     kwargs[field_name] = cls.get_field_value(model_field=model_field)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 436, in get_field_value
app_1  |     return cls.create_factory(model=outer_type).build()
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 513, in build
app_1  |     kwargs[field_name] = cls.get_field_value(model_field=model_field)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 436, in get_field_value
app_1  |     return cls.create_factory(model=outer_type).build()
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 501, in build
app_1  |     model = cls._get_model()
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 199, in _get_model
app_1  |     if is_pydantic_model(model):
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/utils.py", line 27, in is_pydantic_model
app_1  |     return isclass(value) and issubclass(value, BaseModel)
app_1  |   File "/usr/local/lib/python3.10/abc.py", line 123, in __subclasscheck__
app_1  |     return _abc_subclasscheck(cls, subclass)
app_1  | RecursionError: maximum recursion depth exceeded in comparison
provider-integrations_app_1 exited with code 1
```

This is the top:
```
app_1  | 
app_1  | Error while loading the application:
app_1  | 
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 208, in run
app_1  |     self.load()
app_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
app_1  |     return self.load_wsgiapp()
app_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
app_1  |     return util.import_app(self.app_uri)
app_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
app_1  |     mod = importlib.import_module(module)
app_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
app_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
app_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
app_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
app_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
app_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
app_1  |   File "/workspace/src/app/main.py", line 13, in <module>
app_1  |     app = Starlite(
app_1  |   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
app_1  |   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
app_1  |   File "pydantic/decorator.py", line 201, in pydantic.decorator.ValidatedFunction.execute
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/app.py", line 126, in __init__
app_1  |     self.openapi_schema = self.create_openapi_schema_model(openapi_config=openapi_config)
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/app.py", line 306, in create_openapi_schema_model
app_1  |     openapi_schema.paths[route.path_format or "/"] = create_path_item(
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/openapi/path_item.py", line 46, in create_path_item
app_1  |     responses=create_responses(
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/openapi/responses.py", line 156, in create_responses
app_1  |     str(route_handler.status_code): create_success_response(
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/openapi/responses.py", line 48, in create_success_response
app_1  |     schema = create_schema(field=as_parsed_model_field, generate_examples=generate_examples)
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/openapi/schema.py", line 219, in create_schema
app_1  |     schema.examples = create_examples_for_field(field=field)
app_1  |   File "/usr/local/lib/python3.10/site-packages/starlite/openapi/schema.py", line 178, in create_examples_for_field
app_1  |     value = normalize_example_value(ExampleFactory.get_field_value(field))
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 440, in get_field_value
app_1  |     return handle_complex_type(model_field=model_field, model_factory=cls)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/value_generators/complex_types.py", line 82, in handle_complex_type
app_1  |     return handle_container_type(
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/value_generators/complex_types.py", line 62, in handle_container_type
app_1  |     value = handle_complex_type(model_field=random.choice(model_field.sub_fields), model_factory=model_factory)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/value_generators/complex_types.py", line 95, in handle_complex_type
app_1  |     return model_factory.get_field_value(model_field=model_field)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 436, in get_field_value
app_1  |     return cls.create_factory(model=outer_type).build()
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 513, in build
app_1  |     kwargs[field_name] = cls.get_field_value(model_field=model_field)
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 436, in get_field_value
app_1  |     return cls.create_factory(model=outer_type).build()
app_1  |   File "/usr/local/lib/python3.10/site-packages/pydantic_factories/factory.py", line 513, in build
```

**Comment by peterschutt** [comment]
Here's more context:

```python
from uuid import UUID

from pydantic import Field

from app import core

from .types import EntitiesEnum


class Extra(core.Schema):
    sub_entity: "Entity | None"


class Entity(core.Schema):
    id: UUID
    name: str
    owner_id: UUID | None
    provider_id: UUID
    type: EntitiesEnum
    extra: Extra = Field(default_factory=Extra)


Extra.update_forward_refs()
```

If I comment out `Entity.extra` on the `Entity` model, the error goes away.

**Comment by Goldziher** [comment]
I see, ok your recursion error happens because you have a self referncing field - extra, referencing entity, referning extra etc.  This is a known issue with pydantic-factories, I had to work around it in the sqlalchemy stuff.

**Comment by peterschutt** [comment]
Is it something to be fixed or worked-around internally to Starlite? Or does the fix need to come from upstream?

**Comment by Goldziher** [comment]
the issue is upstream. its a complex fix to avoid recursion and the behaviour is not really clear - so Ill see if we can work around it locally.

**Comment by eldano1995** [comment]
I'm getting the same issue when using `msgspec.Struct` (no usage of pydantic):
```
from msgspec import Struct


class EntityV3(Struct):
    name: str
    associated_entities: list["EntityV3"]
```

Is this still an upstream issue?

**Comment by Isuxiz** [comment]
The same type of exception occurred when I used the following type definition:

```python
from __future__ import annotations

from collections.abc import Mapping, Sequence

type JsonNumber = int | float
type JsonSimple = str | JsonNumber | bool | None
type JsonValue = JsonSimple | JsonObject | JsonArray
type JsonObject = Mapping[str, JsonValue]
type JsonArray = Sequence[JsonValue]
```

I was able to fix this by using the type in string constant format instead of variable format:

```python
from __future__ import annotations

from collections.abc import Mapping, Sequence

type JsonNumber = int | float
type JsonSimple = str | JsonNumber | bool | None
type JsonValue = JsonSimple | JsonObject | JsonArray
type JsonObject = Mapping[str, "JsonValue"]
type JsonArray = Sequence["JsonValue"]
```

It looks like the code responsible for parsing the schema does not take into account this recursive definition leading to infinite parsing recursion. I'm not sure where this feature is implemented, but adding a simple hash-based cache mapping may be able to fix this problem (for me).
