### ISSUE TITLE
Apps do not work under uvicorn due to missing httpx in dependencies if starlite is installed without extras

### ISSUE THREAD

**Issue by jtraub** [starlite-api/starlite#531]
**Describe the bug**
Apps do not work under uvicorn due to missing httpx in dependencies if starlite is installed without extras.
As of 1.23.0 I need to install `starlite[testing]` in order to be able to run any app under uvicorn (I haven't tested other ASGI server but I suppose the problem would affect them too).

**To Reproduce**
I am posting entire shell output as I am not 100% sure I am doing everything properly so you can check package versions and so on. 

<details>
  <summary>Reproduction for hello_world app</summary>

```
/tmp/repro 
> python -m venv venv

/tmp/repro took 2s 
> source venv/bin/activate

/tmp/repro via 🐍 (venv) 
> pip install starlite uvicorn
Collecting starlite
  Using cached starlite-1.23.0-py3-none-any.whl (167 kB)
Collecting uvicorn
  Using cached uvicorn-0.18.3-py3-none-any.whl (57 kB)
Collecting pydantic-factories
  Using cached pydantic_factories-1.7.0-py3-none-any.whl (24 kB)
Collecting starlite-multipart
  Using cached starlite_multipart-1.1.0-py3-none-any.whl (14 kB)
Collecting pydantic
  Using cached pydantic-1.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.8 MB)
Collecting pydantic-openapi-schema
  Using cached pydantic_openapi_schema-1.3.0-py3-none-any.whl (45 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting starlette
  Using cached starlette-0.21.0-py3-none-any.whl (64 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting picologging
  Using cached picologging-0.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (155 kB)
Collecting orjson
  Using cached orjson-3.8.0-cp310-cp310-manylinux_2_28_x86_64.whl (146 kB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting faker
  Using cached Faker-15.0.0-py3-none-any.whl (1.6 MB)
Collecting xeger
  Using cached xeger-0.3.5-py3-none-any.whl
Collecting email-validator
  Using cached email_validator-1.3.0-py2.py3-none-any.whl (22 kB)
Collecting anyio<5,>=3.4.0
  Using cached anyio-3.6.1-py3-none-any.whl (80 kB)
Collecting idna>=2.8
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.2.1-py3-none-any.whl (269 kB)
Collecting python-dateutil>=2.4
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: xeger, typing-extensions, sniffio, six, pyyaml, picologging, orjson, idna, h11, dnspython, click, uvicorn, python-dateutil, pydantic, email-validator, anyio, starlite-multipart, starlette, pydantic-openapi-schema, faker, pydantic-factories, starlite
Successfully installed anyio-3.6.1 click-8.1.3 dnspython-2.2.1 email-validator-1.3.0 faker-15.0.0 h11-0.14.0 idna-3.4 orjson-3.8.0 picologging-0.8.1 pydantic-1.10.2 pydantic-factories-1.7.0 pydantic-openapi-schema-1.3.0 python-dateutil-2.8.2 pyyaml-6.0 six-1.16.0 sniffio-1.3.0 starlette-0.21.0 starlite-1.23.0 starlite-multipart-1.1.0 typing-extensions-4.3.0 uvicorn-0.18.3 xeger-0.3.5

/tmp/repro via 🐍 (venv) took 4s 
> wget https://raw.githubusercontent.com/starlite-api/starlite/main/examples/hello_world.py
--2022-09-30 00:52:22--  https://raw.githubusercontent.com/starlite-api/starlite/main/examples/hello_world.py
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 260 [text/plain]
Saving to: ‘hello_world.py’

hello_world.py                                  100%[=====================================================================================================>]     260  --.-KB/s    in 0s      

2022-09-30 00:52:23 (5,83 MB/s) - ‘hello_world.py’ saved [260/260]

> uvicorn hello_world:app --reload
INFO:     Will watch for changes in these directories: ['/tmp/repro']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1910494] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/tmp/repro/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/repro/./hello_world.py", line 2, in <module>
    from starlite import Starlite, get
  File "/tmp/repro/venv/lib/python3.10/site-packages/starlite/__init__.py", line 77, in <module>
    from .testing import RequestFactory, TestClient, create_test_client
  File "/tmp/repro/venv/lib/python3.10/site-packages/starlite/testing.py", line 6, in <module>
    from starlette.testclient import TestClient as StarletteTestClient
  File "/tmp/repro/venv/lib/python3.10/site-packages/starlette/testclient.py", line 15, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
^CINFO:     Stopping reloader process [1910494]

```
</details>

**Comment by Goldziher** [comment]
Yup, my bad - i updated imports I shouldnt have. `v1.23.1` is released with a fix. Please confirm and close this issue.

**Comment by jtraub** [comment]
It works with 1.23.1 now. Thanks!
