### ISSUE TITLE
Error With 'data' kwarg

### ISSUE THREAD

**Issue by stonedprogrammer** [starlite-api/starlite#823]
**Describe the bug**
Unable to route using Starlite due to 'data' kwarg being specified multiple times

**To Reproduce**
1. Create Controller
2. Add a POST route in the controller
3. Create Pydantic model and add it to the route function's args as the 'data' kwarg as specified in https://starlite-api.github.io/starlite/usage/4-request-data/0-request-data/
4. Observe TypeError raised

**Additional context**
Here is the stack trace:
```
ERROR:    | 2022-11-18 09:57:11 | [ExceptionManager] Error
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/starlite/middleware/exceptions/middleware.py", line 47, in __call__
    await self.app(scope, receive, send)
  File "./.venv/lib/python3.10/site-packages/starlite/routes/http.py", line 89, in handle
    response = await self._get_response_for_request(
  File "./.venv/lib/python3.10/site-packages/starlite/routes/http.py", line 138, in _get_response_for_request
    response = await self._call_handler_function(
  File "./.venv/lib/python3.10/site-packages/starlite/routes/http.py", line 166, in _call_handler_function
    response_data = await self._get_response_data(
  File "./.venv/lib/python3.10/site-packages/starlite/routes/http.py", line 206, in _get_response_data
    return await fn()
TypeError: APIController.create_exclusion() got multiple values for argument 'data'
```

Here is the controller:
```
class APIController(Controller):
    path = "/api"

    @post("/create")
    async def create_exclusion(data: Exclusion) -> str:
        return "Hi"
```

and here is the Exclusion Pydantic model and related variables:
```
mac_address = constr(
    strip_whitespace=True,
    to_lower=True,
    min_length=17,
    max_length=17,
    regex="^([0-9a-f]{2}[:]){5}([0-9a-f]{2})$",
)


class Exclusion(BaseModel):
    mac_address: mac_address
    hostname: str
    fixed_address: str
    subnet: str

    @validator("fixed_address")
    def validate_ip(cls, value: str) -> str:
        try:
            IP(value)
        except ValueError:
            raise ValidationException(f"{value} Is Not A Valid IPv4 Address")
        else:
            return value
```

Here is the router:
```
v1_router = Router(path="/v1", route_handlers=[
    APIController,
])
```

Here is the API router:
```
api_router = Router(path="/api", route_handlers=[
    v1_router
])
```

and lastly here is the Starlite application:
```
app = Starlite(route_handlers=[api_router], cors_config=cors, exception_handlers={
    HTTPException: exception_handler,
    Exception: other_handler
})
```

**Comment by stonedprogrammer** [comment]
🤦🏻 Yep, thank you! I was referencing the handler and request data documentation, but forgot to take another look at the Controller documentation.

**Comment by peterschutt** [comment]
No probs!
